### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by seperalta22**
# Portfolio Project: Accessibility

On this branch, we have fixed the accessibility issues, we checked the following: 

- [Page titles](https://www.w3.org/WAI/test-evaluate/preliminary/#title)
- [Image text alternatives** (`alt text`)](https://www.w3.org/WAI/test-evaluate/preliminary/#images)
- [Text headings](https://www.w3.org/WAI/test-evaluate/preliminary/#headings)
- [Color contrast](https://www.w3.org/WAI/test-evaluate/preliminary/#contrast)
- [Resize](https://www.w3.org/WAI/test-evaluate/preliminary/#resize)
- [Interaction](https://www.w3.org/WAI/test-evaluate/preliminary/#interaction) 
- [Moving content](https://www.w3.org/WAI/test-evaluate/preliminary/#moving)
- [Multimedia](https://www.w3.org/WAI/test-evaluate/preliminary/#media)
- [The basic structure of the page](https://www.w3.org/WAI/test-evaluate/preliminary/#structure)

### CODE REVIEW

**Review by mukhammadrizooff — COMMENTED** [review]
Hi @TEAM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

In this milestone, you have built together with your partner, kindly I can not see commits from your partner(`Benjamin Matembe`)!

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by BenjaminMatembe** [comment]
Hi @mukhammadrizooff  and @code_reviewer , we have fixed "I can not see commits from your partner" and the latest commit "[Fix color change](https://github.com/SergioPeralta22/Portfolio/pull/9/commits/1664d33948ef0dd1f23dbce36e0601b580566d2c)"  and the second [Fix accessibility](https://github.com/SergioPeralta22/Portfolio/pull/9/commits/85412b3790db7d882df1025877ce41d1108a88d0) is from me the second partner.

The issue was because I had not configured the changes of user.email on my local machine.

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @Team  , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
 - No linter errors :heavy_check_mark: 
 
## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [x] Kindly make sure to not repeat yourself in CSS. You have multiple same lines of `display: flex` and it doesn't look professional. 

    - Suggestion:
         instead of writing many same lines create one class and name it `flex` and place it in all containers that are using flexbox.
         
      ` .flex {
              display: flex
         }`
 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by medaminedev66** [comment]
Hello @SergioPeralta22 👋,

_This is an additional review as a result of the second opinion request._

For this project, your main objective is to enhance the accessibility of the portfolio. But you are also required to adhere to HTML&CSS best practices, please check out the requirement below: 

image

The change requested by the previous reviewer was mentioned in [HTML&CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md#:~:text=If%20you%20want%20to%20create%20a%20CSS%20rule%20for%20multiple%20elements%2C%20use%20a%20class%20attribute%20instead.%20For%20example%2C%20instead%20of%20using%20color%3A%20%233498db%3B%203%20times) file.


Keep rocking 🚀!

**Comment by seperalta22** [comment]
Hi, @medaminedev66 ! 
 I comply with all the best practices mentioned in the article.
Every time I use Flexbox I use it to chain between 3 and 5 different properties to fulfill different functions. It's like it asks me to use a class for the border color, a class for the border thickness, and another one for the line type, and it could make sense if I was asked to create a tailwind-like framework where to put a class name to each repeating CSS property but this is not the case. 
 You should mention which point of the article I did not follow.

**Comment by medaminedev66** [comment]
Hi @SergioPeralta22,

I was talking about the point number 11. If you are using the same property for multiple elements, you can create a class attribute instead. For example, instead of using display: flex; 3 times:
```css
#intro1 {display: flex; font-size: 10px; font-weight: bold;}
header {display: flex; font-size: 20px; background-color: green;}
#banner {display: flex; font-size: 30px; background-image: url(images/static.jpg);}
```
you can create a class and add it to all element that need to be flex.
```
.flex {display: flex;}
```
Keep rocking 🚀!

**Comment by SergioPeralta22** [comment]
Hi, @medaminedev66 !

Again, I will try to explain it in more detail. Whenever I use flex I use it chained to other properties, like `flex-direction`, `align-items`, `justify-content`, `gap`, etc., I can't leave the parent property separate from the children's logic.
 And also to mention that I mostly use flex to change component behavior in media queries.
 Flexbox is a set of properties not a single property that works in isolation as the example property that changes the `color` and has no relationship with others, in that case, applies to what you say and I have done that with what I consider necessary at the beginning of the document.
If you do not bring me professional documentation that supports what you ask and indicates that I fell in a bad practice I will report you both to student success.

**Comment by BenjaminMatembe** [comment]
Hi @medaminedev66  and @SergioPeralta22 , kindly jump on a zoom call and come to sync with this so that everything is clear on both ends. Because for now its a mis-understanding on both sides.
Thank you!

**Comment by seperalta22** [comment]
Hi, @medaminedev66 !

Again, I will try to explain it in more detail. Whenever I use flex I use it chained to other properties, like flex-direction, align-items, justify-content, gap, etc., I can't leave the parent property separate from the children's logic.
And also to mention that I mostly use Flex to change components in media queries.
Flexbox is a set of properties not a single property that works in isolation as the example property that changes the color and has no relationship with others, in that case, applies to what you say and I have done that with what I consider necessary at the beginning of the document.
For the umpteenth time, I repeat that I opt for the readability and logic of my code. My CSS classes are not too long and I don't use display: flex in isolation repetitively.
If you do not bring me professional documentation that supports what you ask and indicates that I fell into a CSS bad practice in my use of Flexbox I will report you both CR to student success.

**Comment by medaminedev66** [comment]
Hi, @SergioPeralta22 

I understand your perspective, and it's a common approach among developers. However, at Microverse, we adhere to the DRY principle (Don't Repeat Yourself) and CSS best practices. I've noticed that your project contains several repeated CSS rules, such as using `display: flex` 21 times and `--main-color` 6 times. This could potentially compromise the cleanliness of your code.

Please note that I have already sent you the Microverse document outlining our guidelines. If you haven't reviewed it yet, I encourage you to do so. Additionally, you may find the following article helpful as well: [link](https://speckyboy.com/good-bad-css-practices/).

Keep rocking 🚀!

**Review by divinecharlotte — APPROVED** [review]
# Hello @team     😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- Descriptive PR  ✔️
- Workflow used well 👍 


## Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
